version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=age_verification
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  face_service:
    build:
      context: ./backend/face_service
    ports:
      - '5001:5001'
    restart: always

volumes:
  db_data:
