# render.yaml
# Blueprint spec: https://render.com/docs/blueprint-spec

databases:
  # 1. PostgreSQL Database
  - name: age-fraud-db
    plan: free
    postgresMajorVersion: 14
    # The following are optional but recommended for clarity
    # databaseName: agefraud_db 
    # user: agefraud_user

services:
  # 2. Node.js Backend Service
  - type: web
    name: age-fraud-api
    plan: free
    runtime: node
    repo: https://github.com/TinzyWinzy/age-cheat-zim
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: age-fraud-db
          property: connectionString
      - key: CORS_ORIGIN
        value: https://age-cheat-zim.vercel.app/
      - key: ISSUER_PRIVATE_KEY
        sync: false # Secret must be set manually in Render dashboard
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_SECRET_API_KEY
        sync: false 