# render.yaml
# This file configures the services for deployment on Render.
# See https://render.com/docs/blueprint-spec for a full reference.

services:
  # 1. PostgreSQL Database
  - type: pserv
    name: age-fraud-db
    plan: free # Choose your plan: free, starter, etc.
    env: 
      DATABASE_NAME: agefraud
    postgresMajorVersion: 14

  # 2. Node.js Backend Service
  - type: web
    name: age-fraud-api
    plan: free
    runtime: node
    repo: https://github.com/TinzyWinzy/age-cheat-zim # Replace with actual repo if needed
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: age-fraud-db
          property: connectionString

      - key: CORS_ORIGIN
        value: https://your-vercel-frontend-url.vercel.app # Replace with actual frontend URL

      - key: ISSUER_PRIVATE_KEY
        sync: false # Secret must be set manually in Render dashboard

      - key: PINATA_API_KEY
        sync: false

      - key: PINATA_SECRET_API_KEY
        sync: false
